all: main

main: main.cpp base.h samMini.h sam.h joseph.h Whitney.h LTexture.h LTimer.h WhitDot.h Dot.h TextTexture.h So.h SoDot.h
	g++ main.cpp -o main -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf

clean:
	rm main
